version: "3.9"

services:
  # webapi:
  #   # image: node:16-alpine
  #   container_name: webapi
  #   build: ./webapi/
  #   ports:
  #     - 49160:8080
  #   volumes:
  #     - ./webapi:/usr/src/app
  #   environment:
  #     MYSQL_HOST: mysql
  #     MYSQL_USER: root
  #     MYSQL_PASSWORD: secret
  #     MYSQL_DB: todos

  webapp:
    container_name: webapp
    build: ./webapp/
    # image: node:16-alpine
    command: sh -c "npm install --force -save && npm run build"
   
    ports:
      - 3000:3000
    working_dir: /app/webApp/
    volumes:
      - ./webapp:/app/webApp
      # - ./webapp/node_modules
    stdin_open: true
    tty: true

   


  mysql:
    container_name: mysql
    image: mysql:8.0
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: todos


  # webadmin:
  #   container_name: webadmin
  #   build: ./webadmin/
  #   # image: node:16-alpine
  #   # command: sh -c "yarn install && yarn run build"
   
  #   ports:
  #     - 3001:3001
  #   working_dir: /app/webAdmin/
  #   volumes:
  #     - ./webapp:/app/webAdmin
  #     # - ./webapp/node_modules
  #   stdin_open: true
  #   tty: true